services:
- docker
language: go
os:
- linux
cache:
  directories:
    - $GOPATH/.cache/go-build
    - $GOPATH/pkg/mod
go:
- go1.13
go_import_path: github.com/lensesio/lenses-go
install:
  go get golang.org/x/lint/golint

jobs:
  include:
  - stage: Build
    script: REVISION=${TRAVIS_COMMIT} VERSION=${TRAVIS_COMMIT} make cross-build

  - stage: Lint
    script: make lint

  - stage: Tests
    script: make test

  - stage: Build docker
    deploy:
      on:
        tags: false
      provider: script
      script: REVISION=${TRAVIS_COMMIT} make build-linux && VERSION=${TRAVIS_COMMIT} make build-docker

  - stage: Publish docker
    branches:
      only:
        - master 
    deploy: 
      on:
        tags: true
      provider: script
      script: REVISION=${TRAVIS_COMMIT} VERSION=${TRAVIS_TAG} make build-linux && make publish

  - stage: Release
    branches:
      only:
        - master  
    before_deploy: REVISION=${TRAVIS_COMMIT} VERSION=${TRAVIS_TAG} make cross-build; cd bin; for i in *; do tar -czf $i.tar.gz $i; done; ls -1; cd ../;
    deploy:   
      on:
        tags: true
      provider: releases
      name: Release ${TRAVIS_TAG}
      api_key:
        secure: q+kT2K6ZMh4qtiveEmsuC8t/T5IZTZd9zbHeOBQn1YoFt38ym9za94Ehq13jffEvsHOGKX1oc7FxpUkDInDllSXQrYXC2QNEhnA9ZmzijLzyVEKBNir7ts0g0cNXXlEhu+o86z+3nZi14x77NujF+u9ALSOqpLmfo6HmHtCows/Bkf9WC8LQ1wWla4ovh8BkCLe00P+G36tBzpm7khi1In0DaIgQdyG9rUCLQkfKy2smzfq+Cj9R2beXRGP6Zx7so5lwuGCl3xQL7s1LUct/4GyNyTOIpCfZtllJddghw6mY+pJAsurfjP/qdSrGCVj+WAYWh6ZtH0XqqNQe0QnH0NrBC9JCc7oixC/quhz3DEn7ufbUzNxqTOoHWw6wYcJoP2XaUxCXOsQ7KmLmAEa+WtUWxpalHrSScTz6NlxTBFlLGYL1Gl2OxpB4vmOVOS7/5HE1rFJAGYZkpgv4qiD9REoSkD8Qt3eG/BCv9gE7HVgeeiftGD4fEiVxNQw4lt09J/49RZ4ZrGBGcMMd9PGW0cOTYaFoTW+Sy/wKifsUPJSEfm7Avw/LOfuxhDytmbiUIRaFfchfEm8u5UwkOpas8ooGOtwK7bAUG83Le6lndeiAxQyA+0a0vTMkkRqSI1sxN6uV+tflVQZd6ULG3WrdvL/Bqq/ji9gQsIIEDwCavI4= 
      file_glob: true
      file: bin/*.tar.gz
      skip_cleanup: true
      overwrite: true
env:
  global:
    - GO111MODULE=on
    - secure: II8qslnN2wn164YxEEynMJyFmIbNi6IfEX+RRByA2f2VgWaFW1AHeDaSIH6WkXBnQtYm00c2Wx6Rq6TkPcpkkWnGw5jV66jiJ028/mjZSKCHqPWi8QNxvk76ZMEqTYw1Ly2vaM6HMDqQ5gUSFJSuyv56GVc3RkaT8/AltOCppIcoeqQSgjc3A8lU3NrUmx+2N7scAGCNZ/UVckcAghBnjIUW6wnWMQodN6NkKq5RVugt+BPJY+KRBQGD2k7FasixpK2Yru6DEotDqbCWpqBX7SUf0IJh6qok1/BipkHBghK6l2ajF6Rfbmi3WnXhjzm5gT+IsGAZYJvhcc3cwhrlir4BwymGxip57EBMeg/Y2rxVEQB3TVmIvvstuwUyD5BcBa2tqP96cPRcf0G1A//O6EEvh1aW4aE7bhDVWF+rKB4UV6x7QCGR3nwLDkhBxS9dsAEuAoFmIBeUldJJCPivxHyHoMDV7nk1aKna11iJXx9cWlYnPzM8S91mGMSJqRa6c15xOQFfkMMJ1qynCen3xA/ECsLWsCMvuQ6hk7OnsfTRiKPf0GOmM8Y1VCHSPPDcjwjwhfkRdsUnTjyRoYKz1xxtz3BGR+7mhHcNEgphDQM7KwnoleW7TysRL2BKkHbD5Z9lQfMQiS9TQjEwqVw2VDoZj8kV0eqh7eCBV9ViBZc=
    - secure: G7lHGM9M92Bf+DbjUupRpOXes0VGUkzmCV+yngz+4YfFbVlimIEd1H1DFRDZ6Vl/SjBTSQ6xyogiTOUA4FHgdaIp7bF7BnwekJutfZHnbTntT9Em2KfXyLZKTgPfHOQhD+lOqtPpi/UVa5xjn6qYSdWB1D7naoTg8ihSRYn/rJC/P2QByOUBUwd5Ik9YTks0skJRGxjOAmLew5Ym4MWvtlTmLtkVnmWXDgJdhiVq/0aeg31fsYRptoBG95kYvKcmQMza/OdP+0umj0fWujCEZTQvwZK51aJXy/qdAMI/+LEvECe+/fotsiSvns83Po5AnlhX4l/1xGNkeNMUSMCRSLBRn8mZ1k/Gi28W2r22p2cplTvg0Hfdklshl9ob5sl9jAKPmA5lr6JzRjxKU2a2vIWJbtLSM5iHMgFA1l5ACJ3Q1+V9GvVnhEMU59ALjmzXnr+a+fgckABbWo7o20/VfE8ZdDGpryIH3TTVpso8AO9dZMgZ3W2UFqj2I1EK8pB90TLf/H9HC6+iwHNS1VycYV+vNCViqycQ/NnGtxB9A8hcV/o7D7yHCl/N38zYKy3nyTgoOoeOivAMcgYZR4tiUlnUMqoqw947UmUClaDHHbG8Lz9o8gOLQHvZbeHKkve/zG8Id8/tmeYgHYBszJXJzIP33MruTZWlJaTBiZJJNyg=
    
